Repository valor-software/valor-software.github.io, pull requests merged in 2023-01, with the labels that each got.

#221 feat(article): module federation for business
  assets/articles/0052-module-federation-for-the-business/Valor-Business-Zack.png
  assets/articles/0052-module-federation-for-the-business/module-federation-for-the-business.adoc
  assets/articles/0052-module-federation-for-the-business/module-federation-for-the-business.json
  assets/articles/0052-module-federation-for-the-business/zack_chapple.jpeg
Labels: status: done(tested), status: needs review

#222 feat(article): modernization module federation
  assets/articles/0053-modernization-with-module-federation-nx-and-react/Modernization-module-federation.png
  assets/articles/0053-modernization-with-module-federation-nx-and-react/modernization-with-module-federation-nx-and-react.adoc
  assets/articles/0053-modernization-with-module-federation-nx-and-react/modernization-with-module-federation-nx-and-react.json
  assets/articles/0053-modernization-with-module-federation-nx-and-react/zack_chapple.jpeg
Labels: status: done(tested), status: needs review

#227 feat(article): a qwik view of the ranking bar
  assets/articles/0056-a-qwik-view-of-the-ranking-bar/A-Qwik-View-of-the-Ranking-Bar.png
  assets/articles/0056-a-qwik-view-of-the-ranking-bar/Slava_Chub.jpg
  assets/articles/0056-a-qwik-view-of-the-ranking-bar/a-qwik-view-of-the-ranking-bar.adoc
  assets/articles/0056-a-qwik-view-of-the-ranking-bar/a-qwik-view-of-the-ranking-bar.json
  assets/articles/0056-a-qwik-view-of-the-ranking-bar/img1.png
Labels: status: needs review

#223 feature(article): rendering nativescript angular
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/Rendering-NativeScript-Angular.png
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/eduardo.jpg
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img1.jpeg
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img2.jpeg
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img3.png
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img4.png
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img5.png
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img6.png
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img7.png
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/img8.jpeg
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/rendering-nativescript-angular-templates-and-components-into-images.adoc
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/rendering-nativescript-angular-templates-and-components-into-images.json
Labels: status: done(tested), status: needs review

#233 feat(hotfix): the date fixing for the articles
  assets/articles/0046-change-is-the-only-way-to-stay-your-true-self/change-is-the-only-way-to-stay-your-true-self.adoc.json
  assets/articles/0047-introduction-to-swiftui-for-nativescript/introduction-to-swiftui-for-nativescript.json
  assets/articles/0048-webpack-plugin-written-by-chatgpt/webpack-plugin-written-by-chatgpt.json
  assets/articles/0049-module-federation-in-mobile-apps-powered-by-nativescript/module-federation-in-mobile-apps-powered-by-nativescript.json
  assets/articles/0050-introduction-to-jetpack-compose-for-nativescript/introduction-to-jetpack-compose-for-nativescript.json
  assets/articles/0051-tasty-recipes-for-react-d3-the-ranking-bar/tasty-recipes-for-react-and-d3-the-ranking-bar.json
  assets/articles/0052-module-federation-for-the-business/module-federation-for-the-business.json
  assets/articles/0053-modernization-with-module-federation-nx-and-react/modernization-with-module-federation-nx-and-react.json
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/rendering-nativescript-angular-templates-and-components-into-images.json
  assets/articles/0056-a-qwik-view-of-the-ranking-bar/a-qwik-view-of-the-ranking-bar.json
Labels: status: done(tested), status: needs review

#224 feat(portfolio): add dribble and behance links to aoc page
  apps/valor-software-site/src/assets/portfolio/clients/ashes-of-creation.json
  libs/route-pages/ashes-page/src/lib/ashes-page.component.html
Labels: status: done(tested), portfolio

#231 feat(article): valor medusa app and github
  assets/articles/0055-rendering-nativescript-angular-templates-and-components-into-images/rendering-nativescript-angular-templates-and-components-into-images.adoc
  assets/articles/0058-valor-software-medusa-app-and-github/Robson_Muller.jpeg
  assets/articles/0058-valor-software-medusa-app-and-github/imag1.png
  assets/articles/0058-valor-software-medusa-app-and-github/imag2.jpg
  assets/articles/0058-valor-software-medusa-app-and-github/valor-software-medusa-app-and-github.adoc
  assets/articles/0058-valor-software-medusa-app-and-github/valor-software-medusa-app-and-github.json
  assets/articles/0058-valor-software-medusa-app-and-github/valor-software-medusa-app-and-github.png
Labels: status: done(tested)

#235 feat(article): migration repo to an nx monorepo
  assets/articles/0059-migrating-a-repo-to-an-nx-monorepo-while-retaining-history/Guilherme_Tod.png
  assets/articles/0059-migrating-a-repo-to-an-nx-monorepo-while-retaining-history/migrating-a-repo-to-an-nx-monorepo-while-retaining-history.adoc
  assets/articles/0059-migrating-a-repo-to-an-nx-monorepo-while-retaining-history/migrating-a-repo-to-an-nx-monorepo-while-retaining-history.json
  assets/articles/0059-migrating-a-repo-to-an-nx-monorepo-while-retaining-history/migrating-a-repo-to-an-nx-monorepo-while-retaining-history.png
Labels: status: done(tested), status: needs review

#236 feat(article): pitfalls article
  assets/articles/0060-avoiding-common-pitfalls-with-controlvalueaccessors-in-angular/Dmitry_Stepanenko.png
  assets/articles/0060-avoiding-common-pitfalls-with-controlvalueaccessors-in-angular/avoiding-common-pitfalls-with-controlvalueaccessors-in-angular.adoc
  assets/articles/0060-avoiding-common-pitfalls-with-controlvalueaccessors-in-angular/avoiding-common-pitfalls-with-controlvalueaccessors-in-angular.json
  assets/articles/0060-avoiding-common-pitfalls-with-controlvalueaccessors-in-angular/image1.gif
  assets/articles/0060-avoiding-common-pitfalls-with-controlvalueaccessors-in-angular/image2.gif
  assets/articles/0060-avoiding-common-pitfalls-with-controlvalueaccessors-in-angular/image3.gif
  assets/articles/0060-avoiding-common-pitfalls-with-controlvalueaccessors-in-angular/pitfalls.png
Labels: status: done(tested), status: needs review

#240 feat(hotfix): article medusa resources issue fixed
  assets/articles/0054-medusa-resources-overlimit-in-realtime-notification/medusa-resources-overlimit-in-realtime-notification.adoc
Labels: status: needs review

#228 feat(article): medusa the new year dedicated
  assets/articles/0057-medusa-the-new-year-dedicated-release/Medusa_2023.png
  assets/articles/0057-medusa-the-new-year-dedicated-release/Vitor_Bergamo.jpeg
  assets/articles/0057-medusa-the-new-year-dedicated-release/image3.png
  assets/articles/0057-medusa-the-new-year-dedicated-release/medusa-the-new-year-dedicated-release.adoc
  assets/articles/0057-medusa-the-new-year-dedicated-release/medusa-the-new-year-dedicated-release.json
  assets/articles/0057-medusa-the-new-year-dedicated-release/valor_site_new_year.png
Labels: status: to do

#249 feat(article): added module federation with ssr
  assets/articles/0062-module-federation-with-ssr-and-react-18/Alexey_Umanskiy.png
  assets/articles/0062-module-federation-with-ssr-and-react-18/Module-Federation-SSR.png
  assets/articles/0062-module-federation-with-ssr-and-react-18/module-federation-with-ssr-and-react-18.adoc
  assets/articles/0062-module-federation-with-ssr-and-react-18/module-federation-with-ssr-and-react-18.json
Labels: status: done(tested), status: needs review

#238 feat(portfolio): booking app page
  angular.json
  apps/valor-software-site/src/assets/img/bg-img/booking_page/accommodation.png
  apps/valor-software-site/src/assets/img/bg-img/booking_page/background.svg
  apps/valor-software-site/src/assets/img/bg-img/booking_page/diagram_1.svg
  apps/valor-software-site/src/assets/img/bg-img/booking_page/diagram_2.svg
  apps/valor-software-site/src/assets/img/bg-img/booking_page/features_and_capabilities.png
  apps/valor-software-site/src/assets/img/bg-img/booking_page/for_drivers.png
  apps/valor-software-site/src/assets/img/bg-img/booking_page/for_staff.png
  apps/valor-software-site/src/assets/img/bg-img/booking_page/future.svg
  apps/valor-software-site/src/assets/img/bg-img/booking_page/header_bg.png
  apps/valor-software-site/src/assets/img/bg-img/booking_page/medical_services.png
  apps/valor-software-site/src/assets/img/technologies/others/azure.png
  apps/valor-software-site/src/assets/img/technologies/others/python.png
  apps/valor-software-site/src/assets/img/technologies/others/react_clean.png
  apps/valor-software-site/src/assets/img/technologies/others/realm.png
  apps/valor-software-site/src/assets/img/technologies/svg/azure.svg
  apps/valor-software-site/src/assets/img/technologies/svg/python.svg
  apps/valor-software-site/src/assets/img/technologies/svg/react_clean.svg
  apps/valor-software-site/src/assets/img/technologies/svg/realm.svg
  apps/valor-software-site/src/assets/portfolio/clients/booking.json
  apps/valor-software-site/src/assets/portfolio/portfolio.list.ts
  libs/route-pages/blog-portfolio/src/routes.ts
  libs/route-pages/booking-page/.eslintrc.json
  libs/route-pages/booking-page/README.md
  libs/route-pages/booking-page/ng-package.json
  libs/route-pages/booking-page/package.json
  libs/route-pages/booking-page/src/booking-challenge-card/booking-challenge-card.component.html
  libs/route-pages/booking-page/src/booking-challenge-card/booking-challenge-card.component.ts
  libs/route-pages/booking-page/src/booking-page.component.html
  libs/route-pages/booking-page/src/booking-page.component.ts
  libs/route-pages/booking-page/src/booking-page.module.spec.ts
  libs/route-pages/booking-page/src/booking-page.module.ts
  libs/route-pages/booking-page/src/index.ts
  libs/route-pages/booking-page/src/routes.ts
  libs/route-pages/booking-page/src/test-setup.ts
  libs/route-pages/booking-page/tsconfig.json
  libs/route-pages/booking-page/tsconfig.lib.json
  libs/route-pages/booking-page/tsconfig.lib.prod.json
  libs/route-pages/booking-page/tsconfig.spec.json
  tsconfig.base.json
Labels: status: in progress, portfolio

#253 feat(article): leveraging-angular-host-directives
  assets/articles/0063-leveraging-angular-15-host-directives/Denis_Severin.png
  assets/articles/0063-leveraging-angular-15-host-directives/Leveraging-host-directives.png
  assets/articles/0063-leveraging-angular-15-host-directives/leveraging-angular-15-host-directives.adoc
  assets/articles/0063-leveraging-angular-15-host-directives/leveraging-angular-15-host-directives.json
Labels: status: needs review
